#!/usr/bin/env python

import argparse
import sys

parser = argparse.ArgumentParser(description='Display first words of a file')

parser.add_argument('-n', type=int, default=10)
parser.add_argument('infile', nargs='*', type=argparse.FileType('r'),
                    default=[sys.stdin])

ns = parser.parse_args()

for f in ns.infile:
      count = 0
      c = ''
      while count < ns.n:
            c = f.read(1)
            if c == '':
                  break
            # This is naive and doesn't account for multiple spaces.
            if c in ' \t\n\r':
                  count += 1
            sys.stdout.write(c)

sys.stdout.write("\n")
